### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by heddn** [previousnext/drush_cmi_tools#5]
Here's my drushrc.php for a site. As a prerequisite, I've downloaded the drush script and put it in the same folder as the rc script.

``` php
include_once 'drush_cmi_tools.drush.inc';

$ignored_modules = implode(',', [
  'devel',
  'kint',
  'stage_file_proxy',
]);
$ignore_list = (dirname(__FILE__)) . '/config-ignore.yml';
$delete_list = (dirname(__FILE__)) . '/config-delete.yml';
$destination = (dirname(__FILE__)) . '/../config/sync';
$install_once = (dirname(__FILE__)) . '/../config/install_once';
$options['shell-aliases']['too-cexy'] = "cexy --skip-modules=$ignored_modules --destination=$destination --ignore-list=$ignore_list";
$options['shell-aliases']['too-cimy'] = "cimy --source=$destination --install=$install_once --delete-list=$delete_list";
```

Here's my example config-ignore.yml:

``` yaml
ignore:
ignore:
  - devel.settings
  - smtp.settings
  - stage_file_proxy.settings
  - system.menu.devel
```

config-delete.ym (empty for now):

``` yaml
delete: {}
```
